backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\PasswordResetRequestForm;
use backend\models\ResetPasswordForm;

class SiteController extends Controller {
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex() {
        if (\Yii::$app->user->isGuest) {
            $this->layout = "main_public";
            return $this->redirect(['login']);
        } else {
            $this->layout = "main_private";
            return $this->render('index');
        }
    }

    public function actionLogin() {
        if (Yii::$app->user->isGuest) {
            $model = new LoginForm();
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                return $this->goBack();
            } else {
                $this->layout = "main_public";
                return $this->render('login', ['model' => $model]);
            }
        } else {
            $this->layout = "main_private";
            return $this->goHome();
        }
    }

    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->redirect(['login']);
    }

    public function actionRequestPasswordReset() {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
                    'model' => $model,
        ]);
    }

    public function actionResetPassword($token) {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
                    'model' => $model,
        ]);
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
       if (!\Yii::$app->user->isGuest) {
         if(1==1){
        return $this->render('index');
         }
         else{
          //enabled
            $this->layout="mainb";
          return $this->render('indexb');
         }
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
         public function actionDashboard()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('dashboard');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
      public function actionPeople()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('people');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
   public function actionChildren()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('children');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
   public function actionLookup()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('lookup');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
      public function actionAttendance()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('attendance');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
    public function actionOffering()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('offering');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
   public function actionGroup()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('group');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
 public function actionClientshome()
    {
        return $this->render('indexclients');
    }
    public function actionMghome()
    {
        return $this->render('indexmg');
    }
    public function actionPshome()
    {
        return $this->render('indexps');
    }
    public function actionChome()
    {
        return $this->render('indexc');
    }
     public function actionNhome($id)
    {
        return $this->render('indexnomotor',["clientId"=>$id]);
    }
    
    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
          $this->layout="main_home";
        if (!Yii::$app->user->isGuest) {
              $this->layout="main_home";
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

     return $this->redirect(['login']);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
  public function actionChurch()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('church');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
     public function actionImport()
    {
        $model = new \backend\modules\application();

        if ($model->load(Yii::$app->request->post())) {
                   $model->temp= UploadedFile::getInstance($model,'temp');
                 if($model->temp!=""){
                    $model->temp->saveAs('uploadimage/data/'.$model->temp->name);                  
                    $model->temp='uploadimage/data/'.$model->temp->name;
                    $data = \moonland\phpexcel\Excel::widget([
                        'mode' => 'import', 
                        'fileName' => $model->temp, 
                        'setFirstRecordAsKeys' => true, // if you want to set the keys of record column with first record, if it not set, the header with use the alphabet column on excel. 
                        'setIndexSheetByName' => true, // set this if your excel data with multiple worksheet, the index of array will be set with the sheet name. If this not set, the index will use numeric. 
                        //'getOnlySheet' => 'sheet1', // you can set this property if you want to get the specified sheet from the excel data with multiple worksheet.
                    ]);
                   //echo count($data);
                   //$data["Equipment"]
                   // print_r($data);
                   //  exit();
                      $room ="";
                 foreach ($data as $datas){
                  //$namesub=$datas["Asset Category"];
            
             /* $result=Yii::$app->db->createCommand("SELECT * FROM lookup_assetsubcategory where name LIKE '%$namesub%' AND categoryId='{$model->groups}' order by id DESC limit 1")->queryAll();
                    //end
                    if(count($result)>0){
                    foreach($result as   $results){

                    }
                    $subId=$results["id"];

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
//$this->title = 'ASSETS  MANAGEMENT SYSTEM';
//$this->title = 'About';
//$this->params['breadcrumbs'][] = $this->title;
?>
<style>
.icon-btn {
    height: 70px;
    width: 50px;
    margin: 10px 0px 10px 0px;
    border: 1px solid #ddd;
    padding: 16px 0px 0px 0px;
    background-color: #fafafa !important;
    background-image: none !important;
    filter: none !important;
    -webkit-box-shadow: none !important;
    -moz-box-shadow: none !important;
    box-shadow: none !important;
    display: block !important;
    color: #646464 !important;
    text-shadow: none !important;
    text-align: center;
    cursor: pointer;
    position: relative;
    -webkit-transition: all 0.3s ease !important;
    -moz-transition: all 0.3s ease !important;
    -ms-transition: all 0.3s ease !important;
    -o-transition: all 0.3s ease !important;
    transition: all 0.3s ease !important;
}

</style>
 <div class="box box-info">
            <div class="box-header with-border">
               <h3 class="box-title">Home Page</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
             <div class="row-fluid">
                 <a href="<?= Yii::$app->urlManager->createUrl(['site/dashboard','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/analytic.png') ?></i>
                                        <div>Dashboard</div>

                                </a>
                              <a href="<?= Yii::$app->urlManager->createUrl(['/application/default','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/jobcardassign.png') ?></i>
                                        <div>Application</div>

                                </a>
                                <a href="<?= Yii::$app->urlManager->createUrl(['/allocation/default','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                          <i><?php echo Html::img('@web/image/Logbook.png') ?></i>
                                        <div>Allocation</div>

                                </a>
                          <a href="<?= Yii::$app->urlManager->createUrl(['/disbursement/default','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/transaction12.png') ?></i>
                                        <div>Disbursement</div>

                                </a>
             </div>
                
                               <a href="<?= Yii::$app->urlManager->createUrl(['/repayment/default','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/transaction.png') ?></i>
                                        <div>Repayment</div>

                                </a>
                               <a href="<?= Yii::$app->urlManager->createUrl(['site/lookup','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/Set3.png') ?></i>
                                        <div>Look Up</div>

                                </a>
                              <a href="<?= Yii::$app->urlManager->createUrl(['site/index','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/Report.png') ?></i>
                                        <div>Reports</div>

                                </a>
                      
                              </div>
                             </div>
                   
                </div>     

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
 
//use yii\helpers\Html;
//use yii\widgets\ActiveForm;
$this->title = '';
//$this->params['breadcrumbs'][] = $this->title;
?>
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LOGIN</title>
<?= Html::cssFile("@web/login/londinium-theme.css");?>
<?= Html::cssFile("@web/login/styles.css");?>
</head>
<body class="full-width page-condensed">
    
    <div class="login-wrapper">
 <div class="form-box " id="login-box">
     <div class="popup-header">
                <span class="text-semibold">
                 <h3>LOGIN</h3>
                                                                                   
                </span>
                
            </div>
    <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
       
     <div class="well">
                <div class="form-group has-feedback">
                     <?= $form->field($model, 'username') ?>
                    <i class="fa fa-user form-control-feedback"></i>
                </div>
         
                <div class="form-group has-feedback">
               <?= $form->field($model, 'password')->passwordInput() ?>
                  
                </div>
                <div class="row form-actions">
                    <div class="col-xs-6">
                        <div class="checkbox checkbox-success">
                            <label>
                                <input class="styled" type="checkbox">
                                Remember me
                            </label>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <button type="submit" class="btn btn-warning pull-right"><i class="fa   fa-forward"> </i> Login </button>
                    </div>
                   
                </div>
         
            </div>
 
    <?php ActiveForm::end(); ?>
 
</div>
       
    </div>
   
 
     

frontend/views/site/lookup.php
 
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\Customer */

$this->title = 'Look Up Area';
 
$this->params['breadcrumbs'][] = $this->title;
?>
  <div class="box box-info">
            <div class="box-header with-border">
               <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
        <div class="col-md-4">
          <div class="box box-solid">
            <div class="box-header with-border">
             

              <h3 class="box-title">General Look</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                 <ol>
                <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupzone/index','id'=>1])?>">                          
                                       Zone

                                </a></li>
               <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupdeacon/index','id'=>1])?>">                          
                                       Deacon

                                </a></li>
                                
                <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupeducation/index','id'=>1])?>">                          
                                Education

                                </a></li>
                   <li> <a href="<?= Yii::$app->urlManager->createUrl(['organization/view','id'=>1])?>">                          
                                Church Information

                                </a></li>
                     <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupofferingtype/index','id'=>1])?>">                          
                              Offering Type

                                </a></li>
                              <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupposition/index','id'=>1])?>">                          
                                  Position

                                </a></li>
              </ol>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- ./col -->
        <div class="col-md-4">
          <div class="box box-solid">
            <div class="box-header with-border">
            

              <h3 class="box-title">Children Lookup</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <ol>
                <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupchildgroup/index','id'=>1])?>">                          
                                      Group

                                </a></li>
                 <li> <a href="<?= Yii::$app->urlManager->createUrl(['childgevent/index','id'=>1])?>">                          
                                     Events

                                </a></li>
               <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupschool/index','id'=>1])?>">                          
                                    School

                                </a></li>
                
              </ol>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- ./col -->
        <div class="col-md-4">
          <div class="box box-solid">
            <div class="box-header with-border">
            

              <h3 class="box-title">Members Lookup </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
            <ol>
                <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupssch/index','id'=>1])?>">                          
                                 SSCH

                                </a></li>
               <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupservice/index','id'=>1])?>">                          
                                   Service 

                                </a></li>
            
                
              </ol>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <div class="col-md-4">
          <div class="box box-solid">
            <div class="box-header with-border">
           

              <h3 class="box-title">Assets Lookup </h3>
            </div>
            <!-- /.box-header   -->
            <div class="box-body">
            <ol>
                  
              <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupassetcategory/index','id'=>1])?>">                          
                                   Assets Class

                                </a></li>
                    <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupassetsubcategory/index','id'=>1])?>">                          
                                   Assets  Category

                                </a></li>
                <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookuphydropowername/index','id'=>1])?>">                          
                                   Assets Sub Category

                                </a></li>
                <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookuphydropowerstation/index','id'=>1])?>">                          
                                       Station

                                </a></li>
               <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookuphydropowerlocation/index','id'=>1])?>">                          
                                       Power Location

                                </a></li>
                                
                <li> <a href="<?= Yii::$app->urlManager->createUrl(['lookupsubstation/index','id'=>1])?>">                          
                                      Sub-Location

                                </a></li>
              </ol>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
                    
        <!-- ./frame end -->              
    </div>
                    </div>
 </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>